### ISSUE TITLE
Splitting camera.js into a relevant & understandable structure

### ISSUE THREAD

**Issue by arthur-parmentier** [tejaswigowda/posenet-node-max#1]
Hello!

The camera.js file is a complete mess, I just cannot understand what is all the code you have added before the actual code from google to load the model. Could you somehow export that code elsewhere and make the loading process of the file a bit more explicit?

Thank you!

**Comment by tejaswigowda** [comment]
Right now am just using the tensorflow.js sample code. Will try and parse it out!

**Comment by arthur-parmentier** [comment]
Thanks! From what I know, the tensorflow sample code (camera.js demo) is found here: https://github.com/tensorflow/tfjs-models/blob/master/posenet/demos/camera.js and the code is <1000 lines, whereas the camera.js file in your project has to me more than 41 000 lines of codes, among which only the final bit is adapted from the original tensorflow code! I wonder where it comes from, but I am glad anyway it works!

**Comment by tejaswigowda** [comment]
It imports the posenet model, whereas your example links it using `import` statements

**Comment by arthur-parmentier** [comment]
thank you for the clarification!
