### ISSUE TITLE
Give access to posenet settings and FPS

### ISSUE THREAD

**Issue by arthur-parmentier** [tejaswigowda/posenet-node-max#2]
Thank you again for your code. It would be nice to be able to change posenet parameters from the patch, either from dedicated parameters on the patch or from the GUI that is usually attached to the webpage. Do you think it would be possible to access the settings with your patch?

**Comment by arthur-parmentier** [comment]
Taking a look at the FPS would also be very nice, because for now I use an electron process to load an old posenet version, and the good thing about the eternal electron window is that I can force my dedicated GPU to handle it instead of integrated graphics, whereas I am not sure that the window inside max is actually handled by the dedicated GPU as well.

**Comment by tejaswigowda** [comment]
Added fps display and parameter controls. Check it out.

**Comment by arthur-parmentier** [comment]
Perfect, thank you!

**Comment by arthur-parmentier** [comment]
I suggest you to indicate the following on the readme:

For better performance, the MaxHelper process (maxhelper.exe in windows 10) should be assigned to the dedicated GPU instead of integrated (default) one.
